# Bot Setup
bot_mode: starters
# spin
# sweet scent
# bunny hop
# coords
# bonk
# fishing
# starters
# rayquaza
# groudon
# kyogre
# southern island
# mew
# regis
# deoxys runaways
# deoxys reset
# fossil
# castform
# beldum
# johto starters
# buy premier balls
coords:
  pos1:
    - 38
    - 6
  pos2:
    - 39
    - 6
direction: Horizontal
# Vertical
# Horizontal
starter: Torchic
# Torchic
# Mudkip
# Treecko
johto_starter: Totodile
# Cyndaquil
# Totodile
# Chikorita
fossil: Anorith
deoxys_puzzle_solved: false

# User Interface
ui:
  enable: true
  width: 1280
  height: 720

# Web Server (this must be enabled for the UI to work)
server:
  enable: true
  ip: 127.0.0.1
  port: 8888 # The server port must be unique for each instance of the bot you run

bot_instance_id: pokebot_1
# If running multiple instances of the bot, set this to the same `bot_instance_id` string at the top of pokebot.lua (use a unique string per bot instance)

# Autosaves
periodic_save: true
save_every_x_encounters: 1000

# Discord Webhook settings (optional)
discord:
  # Toggle webhooks on/off
  enable: true
  # Your raw webhook URL here, WARNING: this webhook is SENSITIVE! Do not share this value with anyone! If you leak your webhook, anyone will be able to post in your channel
  webhook_url: https://discord.com/api/webhooks/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  # Choose how the IVs will display, either basic layout on one line or formatted for readability
  iv_format: basic
  # "user" or "role", if left empty/invalid: pings are disabled.
  ping_mode: role
  # Discord User/Role ID to ping. Does nothing if "discord_ping_mode" isn't set. Currently supports only one at a time.
  shiny_ping:

# Wild Battles
manual_catch: false
use_spore: true
catch:
- shinies
- perfect_ivs
battle_others: false
pokeball_priority:
- premier_ball
- ultra_ball
- great_ball
- poke_ball
pokeball_override: # Per-species exceptions to pokeball_priority. Falls back to pokeball_priority if it has no Pokeballs in the list
  Abra: 
  - ultra_ball
  - great_ball
cycle_lead_pokemon: true
save_game_after_catch: true

# Pickup
pickup: true
pickup_threshold: 3 # Number of pickup items to find before collection

# Pokemon encounter data logging (logs to stats/encounters/)
log: true

banned_moves:
- None
  # 2-turn
- Bounce
- Dig
- Dive
- Fly
- Sky Attack
- Razor Wind
- Doom Desire
- Solar Beam
  # Inconsistent
- Fake Out
- False Swipe
- Nature Power
- Present
- Destiny Bond
- Wrap
- Snore
- Spit Up
- Bide
- Bind
- Counter
- Future Sight
- Mirror Coat
- Grudge
- Snatch
- Spite
- Curse
- Endeavor
- Revenge
- Assist
- Focus Punch
- Eruption
- Flail
  # Ends battle
- Roar
- Whirlwind
- Selfdestruct
- Perish Song
- Explosion
- Memento

# Cheats
mem_hacks: false # Perform "cheaty" actions such as peeking into eggs to check shininess, knowing instantly which route a roamer is on, instantly locate Feebas tiles etc.
