# Bot config

# Bot mode
# spin, sweet scent, bunny hop, coords, bonk, fishing, starters
# rayquaza, groudon, kyogre, southern island, mew, regis, deoxys runaways
# deoxys reset, fossil, castform, beldum, johto starters, buy premier balls
bot_mode: spin

# Coords - this config is used if `bot_mode` is set to `coords`
# Runs between 2 different x,y coordinates (use `view_coords.lua` in Bizhawk to view coords)
coords:
  pos1:
    - 38
    - 6
  pos2:
    - 39
    - 6

# Bonk direction - this config is used if `bot_mode` is set to `bonk`
# Bonk mode will run left/right or up/down repeatedly until the trainer hits a wall
# horizontal, vertical
bonk_direction: horizontal

# Starters - this config is used if `bot_mode` is set to `starters`
# Choose a Pokemon to soft reset for, save the game with trainer facing the bag
# mudkip, treecko, torchic
starter: mudkip

# Johto starters - this config is used if `bot_mode` is set to `johto starters`
# Choose a Pokemon to soft reset for, save the game with trainer facing the desired Pokeball in Birch's lab
# totodile, cyndaquil, chikorita
johto_starter: totodile

# Fossils - this config is used if `bot_mode` is set to `fossil`
# Save with trainer facing the Fossil Scientist in Devon after handing over the fossil and re-entering the room
# anorith,lileep
fossil: anorith

# Set true if the Deoxys puzzle is solved already and the last save is on the tile in front of the red triangle
deoxys_puzzle_solved: false

# User Interface config
ui:
  enable: true
  width: 1280
  height: 720

# Web Server config (server must be enabled for the UI to work)
server:
  enable: true
  ip: 127.0.0.1
  port: 8888 # The server port must be unique for each instance of the bot you run

# Bot instance ID
# If running multiple instances of the bot
# Set this to the same `bot_instance_id` string at the top of pokebot.lua (use a unique string per bot instance)
bot_instance_id: pokebot_1

# Autosaves
# Auto save every x encounters
# Set to 0 to disable
autosave_encounters: 1000

# Wild Battles
manual_catch: false
use_spore: true
catch_shinies: true
battle_others: false
pokeball_priority:
- premier_ball
- ultra_ball
- great_ball
- poke_ball
pokeball_override: # Per-species exceptions to pokeball_priority. Falls back to pokeball_priority if it has no Pokeballs in the list
  Abra: 
  - ultra_ball
  - great_ball
cycle_lead_pokemon: true
save_game_after_catch: true

# Pickup
pickup: true
# Number of pickup items to find before collection
pickup_threshold: 3

# Pokemon encounter .csv data logging (logs to stats/encounters/)
log: true

# Discord Webhook settings
discord:
  # Toggle all webhooks on/off
  enable: true
  # Your raw webhook URL here, WARNING: this webhook is SENSITIVE! Do not share this value with anyone! If you leak your webhook, anyone will be able to post in your channel
  webhook_url:
  # Choose how the IVs will display, either basic layout on one line or formatted for readability
  iv_format: basic
  # "user" or "role", if left empty/invalid: pings are disabled.
  ping_mode:
  # Discord User/Role ID to ping. Does nothing if "discord_ping_mode" isn't set. Currently supports only one at a time.
  ping_id:
  # Ping the User/Role ID above when a shiny is encountered
  shiny_ping: true
  # Send periodic updates, including phase and total stats every x encounters
  # Set to 0 to disable
  periodic_updates: 1000
  periodic_updates_ping: false
  # Pokemon encounter milestones messages every x encounters
  # Example: "Passed 10,000 total Poochyena encounters!", "Passed 20,000 total Poochyena encounters!" etc.
  # Set to 0 to disable
  pokemon_encounter_milestones: 10000
  pokemon_encounter_milestones_ping: false
  # Total encounter milestones messages every x encounters
  # Example: "Passed 25,000 total encounters!", "Passed 50,000 total encounters!" etc.
  # Set to 0 to disable
  total_encounter_milestones: 25000
  total_encounter_milestones_ping: false

# Banned moves
# Any moves in this list will not be used in battle
banned_moves:
- None
  # 2-turn
- Bounce
- Dig
- Dive
- Fly
- Sky Attack
- Razor Wind
- Doom Desire
- Solar Beam
  # Inconsistent
- Fake Out
- False Swipe
- Nature Power
- Present
- Destiny Bond
- Wrap
- Snore
- Spit Up
- Bide
- Bind
- Counter
- Future Sight
- Mirror Coat
- Grudge
- Snatch
- Spite
- Curse
- Endeavor
- Revenge
- Assist
- Focus Punch
- Eruption
- Flail
  # Ends battle
- Roar
- Whirlwind
- Selfdestruct
- Perish Song
- Explosion
- Memento

# Cheats
# Perform "cheaty" actions such as peeking into eggs to check shininess, knowing instantly which route a roamer is on, instantly locate Feebas tiles etc.
mem_hacks: false
