bot_mode: starters
run_surf:
  coord1:
    - 10
    - 5
  coord2:
    - 3
    - 5
obstructed_dir:
  - Left
  - Right
manual_catch: true
catch:
- shinies
- spore
- perfect_ivs
battle: []
pokeball_priority:
- premier_ball
- ultra_ball
- great_ball
- poke_ball
starter_pokemon: Mudkip
eco_mode: true
game_save:
- save_game_after_catch
encounter_log_limit: 100
log:
- all_encounters
- shiny_encounters
control_map:
  a: x
  b: z
  l: w
  r: e
  up: up
  down: down
  right: right
  left: left
  select: space
  start: enter
  emu_screenshot: f12
  emu_reset_combo:
  - ctrl
  - r
banned_moves:
- None
  # 2-turn
- Bounce
- Dig
- Dive
- Fly
- Sky Attack
- Razor Wind
- Doom Desire
- Solar Beam
  # Inconsistent
- Fake Out
- False Swipe
- Nature Power
- Present
- Destiny Bond
- Wrap
- Snore
- Spit Up
- Bide
- Bind
- Counter
- Future Sight
- Mirror Coat
- Grudge
- Snatch
- Spite
- Curse
- Endeavor
- Revenge
- Assist
- Focus Punch
- Eruption
- Flail
  # Ends battle
- Roar
- Whirlwind
- Selfdestruct
- Perish Song
- Explosion
- Memento
no_sleep_pokemon:
  # Shed Skin
- Metapod
- Kakuna
- Ekans
- Arbok
- Dratini
- Dragonair
- Pupitar
- Silcoon
- Cascoon
- Seviper
  # Vital Spirit
- Mankey
- Primeape
- Electabuzz
- Magmar
- Tyrogue
- Elekid
- Magby
- Vigoroth
  # Insomnia
- Drowzee
- Hypno
- Hoothoot
- Noctowl
- Spinarak
- Ariados
- Murkrow
- Delibird
- Shuppet
- Banette
